employee_index:
    path:     /
    defaults: { _controller: "JardinBundle:employee:index" }
    methods:  GET

employee_show:
    path:     /{id}/show
    defaults: { _controller: "JardinBundle:employee:show" }
    methods:  GET

employee_new:
    path:     /new
    defaults: { _controller: "JardinBundle:employee:new" }
    methods:  [GET, POST]

employee_edit:
    path:     /{id}/edit
    defaults: { _controller: "JardinBundle:employee:edit" }
    methods:  [GET, POST]

employee_delete:
    path:     /{id}/delete
    defaults: { _controller: "JardinBundle:employee:delete" }
    methods:  DELETE
