<?php

namespace JardinBundle\Repository;

/**
 * AbonnmentadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnmentadRepository extends \Doctrine\ORM\EntityRepository
{
}
