<?php

namespace JardinBundle\Repository;

/**
 * enfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class enfantRepository extends \Doctrine\ORM\EntityRepository
{
    public function SumEnfant($id)
    {
      /* $req = $this->createQueryBuilder('e')
        ->select('count(e.id)')
        ->join('e.parents', 'u')
        ->where('u.id = :id')
        ->setParameter('id' , $id)
        ->getQuery()->getScalarResult();
       return ($req);*/
        $query = $this->getEntityManager()->createQuery("select count(q.id) from JardinBundle:enfant q JOIN q.parents u   WHERE(u.id= :id) ")
            ->setParameter('id',$id );
        return $query->getScalarResult();
}
    public function getenfantparent($id)
    {
        $q = $this->getEntityManager()->createQuery(
            "select e from JardinBundle:enfant e JOIN e.parents u WHERE (u.id = :id)"
        )
           ->setParameter('id',$id );
        return $q->getResult();
    }

}
